### ISSUE TITLE
DiscoDeploy's handle_nodeploy_ami and handle_tested_ami are not safe

### ISSUE THREAD

**Issue by IlyaSukhanov** [amplifylitco/asiaq#25]
Both of these methods work in similar way:
1. Change autoscaling group's AMI
2. Scale up number of instances in group (double it)
3. Perform tests
4. Scale back to original group size

The problem is that if there is an error in step 3 or 4 then double the normal instance count is maintained. If this operation is performed multiple times against the autoscaling group number of hosts will start growing exponentially. This is not good.

Possible solutions:
1. Make step 3 and 4 more robust. This is not ideal as failure is always possible even with infinite retry and no timeouts.
2. Instead of looking up current size of autoscaling store the original number somewhere else and use it to figure out intermediate and final size. Ideally a tag or something similar. If on step 0, current actual size > final desired size then fail.

**Comment by jconstance-amplify** [comment]
I'm not sure how solution 2 would work. Don't we always have to look up the current size of the autoscaling group and go off of that because the autoscaling group could change size from when it was originally provisioned? Right now we currently have time-based autoscaling but we will eventually have autoscaling via alarms which I imagine would make this even more problematic.

Is the ultimate solution to this problem implementing blue/green deployment? We could setup some of the monitoring mentioned offline until then to catch this occurring again in the meantime. Perhaps make steps 3 and 4 more robust in the mean time?

**Comment by IlyaSukhanov** [comment]
Yes, with implementation of blue green deployment this issue would go away. Assuming that b/g deploy creates new AG instead of modifying existing ones.

**Comment by jconstance-amplify** [comment]
We met to discuss this and the general consensus was our monitoring should mitigate this from rolling out of control in the future, and that we would like to deprecate this deployment strategy and replace it with ASG-based blue/green deployments in the future. This would merit a major version bump as it could be construed as a breaking change by some.

**Comment by aoskotsky-amplify** [comment]
Fixed with blue/green deployment strategy

**Comment by IlyaSukhanov** [comment]
Sweet! :+1:
